### ISSUE TITLE
Exclude /metrics from being metricized

### ISSUE THREAD

**Issue by piotrmaslanka** [Dronehub/fastapi-satella-metrics#6]
Same thing that was mentioned [here](https://github.com/piotrmaslanka/fastapi-satella-metrics/issues/1). If you're using internal FastAPI dispatch of /metrics you shouldn't  include it in reported metrices.

Originally reported by @guerda.

On a second thought, make that behaviour configurable.

**Comment by piotrmaslanka** [comment]
v2.0 is already on PyPI @guerda

**Comment by guerda** [comment]
Thanks, I will try!
